### ISSUE TITLE
Tag画面のデザインを整える

### ISSUE THREAD

**Issue by ShuheiYoshidaJP** [shinonome-inc/mobile_shu_mogi_Qclient#33]
## 目標
<img width="302" alt=" 2021-02-16 14 05 15" src="https://user-images.githubusercontent.com/62702170/108020586-05b74400-7060-11eb-8f8c-19d7fba2aef3.png">

## 修正ポイント

TabBarの色・アイコンを変更する
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778876943

CollectionViewCellのレイアウトの変更
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778875431

NavigationbarのBackgroundColor
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778881253

TagListCollectionViewCellのborderColorの変更
TagListCollectionViewCellのラベルの色の変更
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#pullrequestreview-590106796

## 作業ブランチ
feature/#33fix_tag_screen_design

**Comment by ShuheiYoshidaJP** [comment]
## TabBarのTagのアイコンを変更

Figmaからエクスポート
TabBarのアイコンを変更

**Comment by ShuheiYoshidaJP** [comment]
@mcz9mm 
CollectionViewのCellのサイズについて疑問点があります。
CellのWidthに関しては可変で、Heightに関しては固定でよろしいでしょうか？
言葉では説明しづらい点がありますので、図の認識で合っていますでしょうか？
よろしくお願いします。
<img width="547" alt="イメージ" src="https://user-images.githubusercontent.com/62702170/108140325-356c5780-7105-11eb-805a-8750d9b8d8f8.png">

**Comment by mcz9mm** [comment]
セルの高さと横幅は固定で、画面サイズに応じて一列に表示される個数が変わるイメージです。
<img width="579" alt="スクリーンショット 2021-02-17 10 02 07" src="https://user-images.githubusercontent.com/11751495/108141507-330afd00-7107-11eb-8352-4628a67dad6e.png">

**Comment by ShuheiYoshidaJP** [comment]
### 目標
水平上隣あうCollectionVewCell同士の間隔を16に設定したい

### 問題
水平上隣あうCollectionVewCell同士の間隔を指定できる便利なメソッドが存在しない

### 対策
Insetを指定できるメソッドは存在するので、

- 画面全体のwidth
- CellのWidth
- 水平上隣あうCollectionVewCell同士の間隔

から左右のinsetを算出する

### 上記の方法に必要な数値
１行あたりのCellの数
１行あたりのCellの数を取得する便利なメソッドが存在しない

### 2つの不等式と1つの等式から１行あたりのCellの数を絞り込む
以下図の式を参照
![Untitled (Draft)-1](https://user-images.githubusercontent.com/62702170/108209335-8879f500-716d-11eb-90e6-78772f8918fd.jpg)

- 画面全体のwidth
- CellのWidth
- 水平上隣あうCollectionVewCell同士の間隔

のみで１行あたりのCellの数を絞り込むことができる

この不等式をコード上に落とすと

```
func calcItemsPerRows() -> Int{
    let margin: CGFloat = 16.0
    let viewWidth = view.frame.width
    let cellWidth: CGFloat = 162
    let maxItemsPerRows = (viewWidth + margin) / (cellWidth + margin)
    let minItemsPerRows = (viewWidth - cellWidth) / (cellWidth + margin)
    let itemsPerRows = (Int(minItemsPerRows) + 1) == Int(maxItemsPerRows) ? Int(maxItemsPerRows) : Int(minItemsPerRows)
    //理論上はInt(maxItemsPerRows)が返される
    return itemsPerRows
}
```

### １行あたりのCellの数が算出できると左右のinsetも算出できる

![IMG_C2274D7B1F62-1](https://user-images.githubusercontent.com/62702170/108209964-48ffd880-716e-11eb-8d12-877d6ca3c724.jpeg)
これをコード上に落とすと

```
func calcLeftAndRightInsets(itemsPerRows: Int) -> CGFloat {
    let margin: CGFloat = 16.0
    let viewWidth = view.frame.width
    let cellWidth: CGFloat = 162
    let inset = 0.5 * (viewWidth + margin - CGFloat(itemsPerRows) * (cellWidth + margin))
    return inset
}
```

### UICollectionViewDelegateFlowLayoutのメソッドを使ってinsetを設定する
使用メソッド
`func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) ->`

**Comment by ShuheiYoshidaJP** [comment]
### navigationBarの色を変更
#31 で実装したnavigationBarの色を変える拡張機能を使った

**Comment by ShuheiYoshidaJP** [comment]
### TagListCollectionViewCellのborderColorの変更・ラベルの色の変更
borderColor→EOEOEO
ラベルの色→828282
