### ISSUE TITLE
MyPage画面のデザインを整える

### ISSUE THREAD

**Issue by ShuheiYoshidaJP** [shinonome-inc/mobile_shu_mogi_Qclient#36]
## 目標
<img width="313" alt=" 2021-02-19 10 25 09" src="https://user-images.githubusercontent.com/62702170/108443804-c88bc580-729c-11eb-8306-7faf42ae8362.png">

## 修正ポイント
投稿記事セクションの追加
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778876381

TabBarの色・アイコンを変更する
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778876943

NavigationBarのbackgroundColorを変更する
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778881253

記事セルのレイアウト変更
https://github.com/shinonome-inc/mobile_shu_mogi_Qclient/pull/30#issuecomment-778877346

プロフィールのレイアウト変更
Figmaのデザインとよく比較する

**Comment by ShuheiYoshidaJP** [comment]
@mcz9mm 
MyPageのデザインに関する提案です。

記事セルで表示されるアイコンは、
MyPage画面トップで表示されるアイコンと同じです。

なので、記事セルで表示させるアイコンに関しては
不要かと思われます。

**Comment by mcz9mm** [comment]
レイアウトの修正をしました
<img width="648" alt="スクリーンショット 2021-02-19 12 39 22" src="https://user-images.githubusercontent.com/11751495/108454362-9172df80-72af-11eb-9810-99e143177c9a.png">

**Comment by mcz9mm** [comment]
ユーザーID部分も不要なので削除しています。

**Comment by ShuheiYoshidaJP** [comment]
### TableViewCellレイアウト修正
ラベルの左マージン16px
ラベルheight変更
フォントサイズ変更
discriptionLabelとlikeLabelを統合

**Comment by ShuheiYoshidaJP** [comment]
### tableViewのセクションを設定
コード（MyPageViewController.swift）に実装した

**Comment by ShuheiYoshidaJP** [comment]
### TabBarのアイコンを変更
FigmaからUserの画像をエクスポート
xcassetsに追加
MyPage→マイページに変更

**Comment by ShuheiYoshidaJP** [comment]
### プロフィールのレイアウトを大幅に変更した

### フォローフォロワーボタンのタイトルを変更
数字とフォロー中・フォロワーでスタイルが違う
↓参考サイト
[NSAttributedStringをcustomKeyで自在に操る話【Swift 4】](https://qiita.com/ComeYummy/items/fe2a29b432ca4b6b17b2)
NSMutableAttributedStringを使って実装した
